# Use root/example as user/password credentials
version: '3.1'

services:

  postgres:
    image: postgres
    deploy:
      condition: on-failure
    environment:
      #MYSQL_ROOT_PASSWORD: password
      #MYSQL_DATABASE: demo
      #MYSQL_USER: demo_user
      #MYSQL_PASSWORD: demo_pass
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
      POSTGRES_DB: demo
    networks: 
      - default

  demo-postgres:
    image: sunrays86/spring-boot-docker-mysql
    deploy:
      condition: on-failure
    ports:
      - 8084:8080
    depends_on: 
      - postgres
    links: 
      - postgres:demo-postgres
    networks: 
      - default
