# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    image: postgres
    restart: always
    environment:
      #MYSQL_ROOT_PASSWORD: password
      #MYSQL_DATABASE: demo
      #MYSQL_USER: demo_user
      #MYSQL_PASSWORD: demo_pass
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
      POSTGRES_DB: demo
    networks: 
      - default

  demo-mysql:
    image: demo_mysql
    restart: always
    ports:
      - 8084:8080
    depends_on: 
      - mysql
    links: 
      - mysql:demo-mysql
    networks: 
      - default
